### ISSUE TITLE
Unit tests checklist 🤔☑︎😓

### ISSUE THREAD

**Issue by rwanyoike** [rwanyoike/time2relax#2]
## Misc

- [x] encode_att_id()
- [x] encode_doc_id()
- [x] encode_uri_component()
- [x] get_db_host()
- [x] get_db_name()
- [x] handle_query_args()
- [x] get_http_exception()
